import { isPostgresMode, query } from "../../../lib/db";

async function ensureAuthTables() {
  if (isPostgresMode) {
    await query(`
      CREATE TABLE IF NOT EXISTS user_credits (
        email TEXT PRIMARY KEY,
        password TEXT NOT NULL DEFAULT '12345688',
        credits INTEGER NOT NULL DEFAULT 0,
        created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
      )
    `);
    await query(`
      CREATE TABLE IF NOT EXISTS credit_transactions (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        email TEXT NOT NULL,
        type TEXT NOT NULL,
        amount INTEGER NOT NULL,
        balance_after INTEGER NOT NULL,
        description TEXT NULL,
        created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
      )
    `);
    return;
  }

  await query(`
    CREATE TABLE IF NOT EXISTS user_credits (
      email VARCHAR(255) PRIMARY KEY,
      password VARCHAR(255) NOT NULL DEFAULT '12345688',
      credits INT NOT NULL DEFAULT 0,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    )
  `);
  await query(`
    CREATE TABLE IF NOT EXISTS credit_transactions (
      id INT AUTO_INCREMENT PRIMARY KEY,
      email VARCHAR(255) NOT NULL,
      type VARCHAR(50) NOT NULL,
      amount INT NOT NULL,
      balance_after INT NOT NULL,
      description TEXT NULL,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )
  `);
}

export default async function handler(req, res) {
  if (req.method !== "POST") {
    return res.status(405).json({ success: false, error: "Method Not Allowed" });
  }

  const { email, password } = req.body || {};
  if (!email || !password) {
    return res.status(400).json({ success: false, error: "账号和密码不能为空！" });
  }

  try {
    await ensureAuthTables();

    const rows = await query("SELECT password, credits FROM user_credits WHERE email = ?", [email]);
    if (rows && rows.length > 0) {
      if (rows[0].password !== password) {
        return res.status(401).json({ success: false, error: "密码错误，请重试！" });
      }
      return res.status(200).json({
        success: true,
        credits: rows[0].credits || 0,
        isNewUser: false,
      });
    }

    await query("INSERT INTO user_credits (email, password, credits) VALUES (?, ?, ?)", [email, password, 30]);
    await query(
      "INSERT INTO credit_transactions (email, type, amount, balance_after, description) VALUES (?, ?, ?, ?, ?)",
      [email, "gift", 30, 30, "FDE FAN Diagnosis welcome quota"]
    );

    return res.status(200).json({
      success: true,
      credits: 30,
      isNewUser: true,
    });
  } catch (error) {
    console.error("[Diagnosis Auth] Pre-check error:", error);
    return res.status(500).json({ success: false, error: "登录失败，请检查服务配置或稍后重试" });
  }
}
